[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "cloudpulse-cli"
version = "0.1.0"
description = "A lightweight CLI for monitoring website and API health, latency, and availability."
readme = "README.md"
requires-python = ">=3.10"
authors = [
    {name = "Paul Revanth Madasu"}
]
keywords = ["monitoring", "health-check", "cli", "devops", "availability"]

[project.scripts]
cloudpulse = "cloudpulse.cli:main"

[tool.setuptools.packages.find]
include = ["cloudpulse*"]


[project.urls]
Homepage = "https://github.com/NAU-OSS/CloudPulse"
Repository = "https://github.com/NAU-OSS/CloudPulse"
Issues = "https://github.com/NAU-OSS/CloudPulse/issues"
